#!/usr/bin/env node
/**
 * build-gallery.mjs — generate data.js for dossier.html from the source of truth.
 *
 * Reads portraits/roster.json (64 role identities), examples/*.json (full dossiers — only
 * roles whose aptitudes are filled, e.g. judge), house-style.json (disposition/grade flavor),
 * and checks portraits/renders/<id>.png for which portraits exist. Emits data.js with
 * window.ROSTER / window.DOSSIERS / window.HOUSE / window.PALETTE. Re-run after the roster,
 * portraits, or aptitude data change.  Usage:  node build-gallery.mjs
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { renderDossierBlock } from '../src/dossier-block.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const roster = JSON.parse(readFileSync(join(HERE, 'portraits', 'roster.json'), 'utf8'));
delete roster._note;

const exDir = join(HERE, 'examples');
const DOSSIERS = {};
for (const f of readdirSync(exDir).filter((f) => f.endsWith('.json'))) {
  DOSSIERS[f.replace('.json', '')] = JSON.parse(readFileSync(join(exDir, f), 'utf8'));
}

const house = JSON.parse(readFileSync(join(HERE, 'portraits', 'house-style.json'), 'utf8'));
const HOUSE = { disposition_expression: house.disposition_expression, grade_cue: house.grade_cue };

// Portraits are web-optimized JPGs committed under portraits/web/ (~6 MB total). The full-res
// PNG masters stay local + gitignored; regenerate web/ via optimize-portraits.py.
const webDir = join(HERE, 'portraits', 'web');
const ROSTER = {};
for (const [id, r] of Object.entries(roster)) {
  ROSTER[id] = { id, ...r, portrait: existsSync(join(webDir, `${id}.jpg`)) ? `portraits/web/${id}.jpg` : null };
}

// crew → accent hex (mirrors house-style pack_palette names)
const PALETTE = {
  core: '#9fb2c9', engineering: '#4fc3f7', design: '#e06ad0', marketing: '#ff7a59',
  product: '#2dd4bf', research: '#f5b544', growth: '#34e0a1', treatment: '#d9b44a',
  'deep-audit': '#6f8fd0', brainstorm: '#c08bf0', swarm: '#ff9d4d',
};

// The exact Operating Posture text dispatch injects per role — the gallery renders this
// verbatim (honesty contract: what you read is what the model gets). Requires
// build-runtime.mjs to have run first (renderDossierBlock reads src/role-dossiers.json).
const INJECTED = {};
for (const d of Object.values(DOSSIERS)) {
  const block = renderDossierBlock(d.role);
  if (block) INJECTED[d.id] = block;
}

const out =
  `// GENERATED by build-gallery.mjs — do not hand-edit. Re-run to refresh.\n` +
  `window.ROSTER = ${JSON.stringify(ROSTER, null, 2)};\n` +
  `window.DOSSIERS = ${JSON.stringify(DOSSIERS, null, 2)};\n` +
  `window.INJECTED = ${JSON.stringify(INJECTED, null, 2)};\n` +
  `window.HOUSE = ${JSON.stringify(HOUSE, null, 2)};\n` +
  `window.PALETTE = ${JSON.stringify(PALETTE, null, 2)};\n`;
writeFileSync(join(HERE, 'data.js'), out);

const withPortrait = Object.values(ROSTER).filter((r) => r.portrait).length;
console.log(`data.js: ${Object.keys(ROSTER).length} roles, ${Object.keys(DOSSIERS).length} full dossier(s), ${withPortrait} portraits`);
